import Head from "next/head";
import { ThemeProvider } from "styled-components";
import { defaultTheme } from "@/styles/theme";

export default function Home() {
  return (
    <ThemeProvider theme={defaultTheme}>
      <Head>
        <title>Coffe Delivery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <h1>Hello World</h1>
      </main>
    </ThemeProvider>
  );
}
